name: piaf
description: A privacy focused social media based on matrix

publish_to: "none"

version: 2.0.2+16

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Matrix
  matrix:
    git: https://github.com/famedly/matrix-dart-sdk
  matrix_homeserver_recommendations: ^0.3.0


  # Cryptography
  encrypt: ^5.0.1
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0

  # Storage and database
  sqflite_common_ffi: ^2.3.2+1
  sqflite_sqlcipher: ^3.0.0
  localstorage: ^6.0.0
  flutter_secure_storage: ^9.0.0

  provider: ^6.0.1

  # navigator
  auto_route: ^9.2.0

  # web navigator for SSO
  webview_flutter: ^4.0.1
  url_launcher: ^6.0.3
  desktop_webview_window: ^0.2.0

  # Post formating
  flutter_markdown:
  emoji_picker_flutter: ^4.3.0

  # images
  image_picker:
  file_picker: ^9.2.2
  path_provider: ^2.0.5
  native_imaging:
    git:
      url: git@github.com:henri2h/dart_native_imaging.git
      ref: henri2h/v1_removal
  # Intl
  intl: ^0.20.2
  timeago: ^3.0.2

  # Cache
  flutter_cache_manager: ^3.0.1
  cached_network_image: ^3.0.0

  # Notifications
  flutter_local_notifications: ^18.0.1
  # unifiedpush: ^5.0.0
  desktop_notifications: ^0.6.3

  # Calls
  callkeep: # need a new release after https://github.com/flutter-webrtc/callkeep/pull/190
    #git: https://github.com/flutter-webrtc/callkeep.git
    git:
      url: https://github.com/henri2h/callkeep
      ref: henri2h/v1_removal
  flutter_webrtc:
    git:
      url: git@github.com:henri2h/flutter-webrtc.git
      ref: henri2h/v1_removal
  flutter_ringtone_player:
    git: 
      url: https://github.com/yaakovschectman/flutter_ringtone_player.git
      ref: v1_removal
  # Lists
  scrollview_observer: ^1.19.0

  # Media 
  camera: ^0.11.0
  chewie: ^1.7.4
  photo_manager: ^3.0.0-dev.4
  photo_manager_image_provider: ^2.1.0
  video_player: ^2.5.3
  video_compress:
    git: https://github.com/jonataslaw/VideoCompress.git
    # Wating for V1 removal commit to be released
  just_audio: ^0.9.20
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4 
  # Select according to https://github.com/media-kit/media-kit/tree/main/video_player_media_kit
  media_kit_libs_android_video: any
  media_kit_libs_linux: any

  # Chat UI
  flutter_chat_bubble: ^2.0.2
  flutter_html: ^3.0.0-beta.2
  universal_html: ^2.2.4

  # UI
  adaptive_dialog: ^2.0.0
  future_loading_dialog: ^0.3.0
  flutter_typeahead: ^5.0.1
  another_flushbar: ^1.10.25
  auto_size_text: ^3.0.0
  swipe_to: ^1.0.5
  shimmer: ^3.0.0
  dynamic_color: ^1.6.6
  
  # Settings
  settings_ui: ^2.0.2
  package_info_plus: ^8.0.0
  permission_handler: ^11.1.0

# Override due to https://github.com/mogol/flutter_secure_storage/issues/616
  audio_session: any

  flutter_slidable: ^4.0.0
  wakelock_plus: ^1.1.4
  flutter_blurhash: ^0.8.1

  multi_split_view: ^3.0.1
  pasteboard: ^0.3.0
  flutter_highlighter: ^0.1.1
  flutter_foreground_task: ^8.10.4
  share_plus: ^10.0.0
  flutter_html_table: ^3.0.0-beta.2
  linkify: ^5.0.0
  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^6.0.3
  desktop_lifecycle: ^0.1.0
  flutter_datetime_picker_plus: ^2.1.0
  flutter_math_fork: ^0.7.2
  shared_preferences: ^2.3.2
  http: ^0.13.6
  webrtc_interface: ^1.2.0
  blurhash_dart: ^1.2.1
  path: ^1.9.0
  sqlcipher_flutter_libs: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.1.2
  import_sorter: ^4.6.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.1.4
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/verification.png
    - assets/sas-emoji.json
    - assets/bg_paris.jpg
    - assets/login_background.jpg
    - assets/piaf.jpg


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

