var olm_exports = {};
var onInitSuccess;
var onInitFail;

var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var a;a||(a=typeof Module !== 'undefined' ? Module : {});var aa,ba;a.ready=new Promise(function(b,c){aa=b;ba=c});var g;if("undefined"!==typeof window)g=function(b){window.crypto.getRandomValues(b)};else if(module.exports){var ca=require("crypto");g=function(b){var c=ca.randomBytes(b.length);b.set(c)};process=global.process}else throw Error("Cannot find global to attach library to");
if("undefined"!==typeof OLM_OPTIONS)for(var da in OLM_OPTIONS)OLM_OPTIONS.hasOwnProperty(da)&&(a[da]=OLM_OPTIONS[da]);a.onRuntimeInitialized=function(){h=a._olm_error();olm_exports.PRIVATE_KEY_LENGTH=a._olm_pk_private_key_length();onInitSuccess&&onInitSuccess()};a.onAbort=function(b){onInitFail&&onInitFail(b)};var l={},m;for(m in a)a.hasOwnProperty(m)&&(l[m]=a[m]);var fa=!1,n=!1,ha=!1,ia=!1;fa="object"===typeof window;n="function"===typeof importScripts;
ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ia=!fa&&!ha&&!n;var q="",ja,ka,la,ma;
if(ha)q=n?require("path").dirname(q)+"/":__dirname+"/",ja=function(b,c){la||(la=require("fs"));ma||(ma=require("path"));b=ma.normalize(b);return la.readFileSync(b,c?null:"utf8")},ka=function(b){b=ja(b,!0);b.buffer||(b=new Uint8Array(b));b.buffer||r("Assertion failed: undefined");return b},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",r),a.inspect=function(){return"[Emscripten Module object]"};
else if(ia)"undefined"!=typeof read&&(ja=function(b){return read(b)}),ka=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");"object"===typeof b||r("Assertion failed: undefined");return b},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||n)n?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),
_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.lastIndexOf("/")+1):q="",ja=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},n&&(ka=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});a.print||console.log.bind(console);var na=a.printErr||console.warn.bind(console);for(m in l)l.hasOwnProperty(m)&&(a[m]=l[m]);l=null;var oa;a.wasmBinary&&(oa=a.wasmBinary);var noExitRuntime;
a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);"object"!==typeof WebAssembly&&r("no native wasm support detected");
function t(b){var c="i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":u[b>>0]=0;break;case "i8":u[b>>0]=0;break;case "i16":pa[b>>1]=0;break;case "i32":w[b>>2]=0;break;case "i64":qa=[0,(x=0,1<=+Math.abs(x)?0<x?(Math.min(+Math.floor(x/4294967296),4294967295)|0)>>>0:~~+Math.ceil((x-+(~~x>>>0))/4294967296)>>>0:0)];w[b>>2]=qa[0];w[b+4>>2]=qa[1];break;case "float":ra[b>>2]=0;break;case "double":sa[b>>3]=0;break;default:r("invalid type for setValue: "+c)}}
function ta(b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":return u[b>>0];case "i8":return u[b>>0];case "i16":return pa[b>>1];case "i32":return w[b>>2];case "i64":return w[b>>2];case "float":return ra[b>>2];case "double":return sa[b>>3];default:r("invalid type for getValue: "+c)}return null}var ua,va=!1,wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function y(b,c){if(b){var d=z,e=b+c;for(c=b;d[c]&&!(c>=e);)++c;if(16<c-b&&d.subarray&&wa)b=wa.decode(d.subarray(b,c));else{for(e="";b<c;){var f=d[b++];if(f&128){var k=d[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var p=d[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|p:(f&7)<<18|k<<12|p<<6|d[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}b=e}}else b="";return b}
function A(b,c,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var k=0;k<b.length;++k){var p=b.charCodeAt(k);if(55296<=p&&57343>=p){var v=b.charCodeAt(++k);p=65536+((p&1023)<<10)|v&1023}if(127>=p){if(d>=e)break;c[d++]=p}else{if(2047>=p){if(d+1>=e)break;c[d++]=192|p>>6}else{if(65535>=p){if(d+2>=e)break;c[d++]=224|p>>12}else{if(d+3>=e)break;c[d++]=240|p>>18;c[d++]=128|p>>12&63}c[d++]=128|p>>6&63}c[d++]=128|p&63}}c[d]=0;return d-f}
function B(b){for(var c=0,d=0;d<b.length;++d){var e=b.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:c+4}return c}function xa(b,c){for(var d=0;d<b.length;++d)u[c++>>0]=b.charCodeAt(d)}var ya,u,z,pa,w,ra,sa;
function za(){var b=ua.buffer;ya=b;a.HEAP8=u=new Int8Array(b);a.HEAP16=pa=new Int16Array(b);a.HEAP32=w=new Int32Array(b);a.HEAPU8=z=new Uint8Array(b);a.HEAPU16=new Uint16Array(b);a.HEAPU32=new Uint32Array(b);a.HEAPF32=ra=new Float32Array(b);a.HEAPF64=sa=new Float64Array(b)}var Aa,Ba=[],Ca=[],Da=[],Ea=[];function Ga(){var b=a.preRun.shift();Ba.unshift(b)}var C=0,Ha=null,Ia=null;a.preloadedImages={};a.preloadedAudios={};
function r(b){if(a.onAbort)a.onAbort(b);na(b);va=!0;b=new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");ba(b);throw b;}function Ja(b){var c=D;return String.prototype.startsWith?c.startsWith(b):0===c.indexOf(b)}function Ka(){return Ja("data:application/octet-stream;base64,")}var D="olm.wasm";if(!Ka()){var La=D;D=a.locateFile?a.locateFile(La,q):q+La}
function Ma(){try{if(oa)return new Uint8Array(oa);if(ka)return ka(D);throw"both async and sync fetching of the wasm failed";}catch(b){r(b)}}function Na(){return oa||!fa&&!n||"function"!==typeof fetch||Ja("file://")?Promise.resolve().then(Ma):fetch(D,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+D+"'";return b.arrayBuffer()}).catch(function(){return Ma()})}var x,qa;
function Oa(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var d=c.Kb;"number"===typeof d?void 0===c.Jb?Aa.get(d)():Aa.get(d)(c.Jb):d(void 0===c.Jb?null:c.Jb)}}}function E(b){var c=Array(B(b)+1);b=A(b,c,0,c.length);c.length=b;return c}Ca.push({Kb:function(){Pa()}});
var Qa={a:function(b,c,d){z.copyWithin(b,c,c+d)},b:function(b){b>>>=0;var c=z.length;if(2147483648<b)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,b+100663296);e=Math.max(16777216,b,e);0<e%65536&&(e+=65536-e%65536);a:{try{ua.grow(Math.min(2147483648,e)-ya.byteLength+65535>>>16);za();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1}};
(function(){function b(f){a.asm=f.exports;ua=a.asm.c;za();Aa=a.asm.d;C--;a.monitorRunDependencies&&a.monitorRunDependencies(C);0==C&&(null!==Ha&&(clearInterval(Ha),Ha=null),Ia&&(f=Ia,Ia=null,f()))}function c(f){b(f.instance)}function d(f){return Na().then(function(k){return WebAssembly.instantiate(k,e)}).then(f,function(k){na("failed to asynchronously prepare wasm: "+k);r(k)})}var e={a:Qa};C++;a.monitorRunDependencies&&a.monitorRunDependencies(C);if(a.instantiateWasm)try{return a.instantiateWasm(e,
b)}catch(f){return na("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return oa||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||Ja("file://")||"function"!==typeof fetch?d(c):fetch(D,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(c,function(k){na("wasm streaming compile failed: "+k);na("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(ba);return{}})();
var Pa=a.___wasm_call_ctors=function(){return(Pa=a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};a._olm_get_library_version=function(){return(a._olm_get_library_version=a.asm.f).apply(null,arguments)};a._olm_error=function(){return(a._olm_error=a.asm.g).apply(null,arguments)};a._olm_account_last_error=function(){return(a._olm_account_last_error=a.asm.h).apply(null,arguments)};a._olm_session_last_error=function(){return(a._olm_session_last_error=a.asm.i).apply(null,arguments)};
a._olm_utility_last_error=function(){return(a._olm_utility_last_error=a.asm.j).apply(null,arguments)};a._olm_account_size=function(){return(a._olm_account_size=a.asm.k).apply(null,arguments)};a._olm_session_size=function(){return(a._olm_session_size=a.asm.l).apply(null,arguments)};a._olm_utility_size=function(){return(a._olm_utility_size=a.asm.m).apply(null,arguments)};a._olm_account=function(){return(a._olm_account=a.asm.n).apply(null,arguments)};
a._olm_session=function(){return(a._olm_session=a.asm.o).apply(null,arguments)};a._olm_utility=function(){return(a._olm_utility=a.asm.p).apply(null,arguments)};a._olm_clear_account=function(){return(a._olm_clear_account=a.asm.q).apply(null,arguments)};a._olm_clear_session=function(){return(a._olm_clear_session=a.asm.r).apply(null,arguments)};a._olm_clear_utility=function(){return(a._olm_clear_utility=a.asm.s).apply(null,arguments)};
a._olm_pickle_account_length=function(){return(a._olm_pickle_account_length=a.asm.t).apply(null,arguments)};a._olm_pickle_session_length=function(){return(a._olm_pickle_session_length=a.asm.u).apply(null,arguments)};a._olm_pickle_account=function(){return(a._olm_pickle_account=a.asm.v).apply(null,arguments)};a._olm_pickle_session=function(){return(a._olm_pickle_session=a.asm.w).apply(null,arguments)};a._olm_unpickle_account=function(){return(a._olm_unpickle_account=a.asm.x).apply(null,arguments)};
a._olm_unpickle_session=function(){return(a._olm_unpickle_session=a.asm.y).apply(null,arguments)};a._olm_create_account_random_length=function(){return(a._olm_create_account_random_length=a.asm.z).apply(null,arguments)};a._olm_create_account=function(){return(a._olm_create_account=a.asm.A).apply(null,arguments)};a._olm_account_identity_keys_length=function(){return(a._olm_account_identity_keys_length=a.asm.B).apply(null,arguments)};
a._olm_account_identity_keys=function(){return(a._olm_account_identity_keys=a.asm.C).apply(null,arguments)};a._olm_account_signature_length=function(){return(a._olm_account_signature_length=a.asm.D).apply(null,arguments)};a._olm_account_sign=function(){return(a._olm_account_sign=a.asm.E).apply(null,arguments)};a._olm_account_one_time_keys_length=function(){return(a._olm_account_one_time_keys_length=a.asm.F).apply(null,arguments)};
a._olm_account_one_time_keys=function(){return(a._olm_account_one_time_keys=a.asm.G).apply(null,arguments)};a._olm_account_mark_keys_as_published=function(){return(a._olm_account_mark_keys_as_published=a.asm.H).apply(null,arguments)};a._olm_account_max_number_of_one_time_keys=function(){return(a._olm_account_max_number_of_one_time_keys=a.asm.I).apply(null,arguments)};
a._olm_account_generate_one_time_keys_random_length=function(){return(a._olm_account_generate_one_time_keys_random_length=a.asm.J).apply(null,arguments)};a._olm_account_generate_one_time_keys=function(){return(a._olm_account_generate_one_time_keys=a.asm.K).apply(null,arguments)};a._olm_create_outbound_session_random_length=function(){return(a._olm_create_outbound_session_random_length=a.asm.L).apply(null,arguments)};
a._olm_create_outbound_session=function(){return(a._olm_create_outbound_session=a.asm.M).apply(null,arguments)};a._olm_create_inbound_session=function(){return(a._olm_create_inbound_session=a.asm.N).apply(null,arguments)};a._olm_create_inbound_session_from=function(){return(a._olm_create_inbound_session_from=a.asm.O).apply(null,arguments)};a._olm_session_id_length=function(){return(a._olm_session_id_length=a.asm.P).apply(null,arguments)};
a._olm_session_id=function(){return(a._olm_session_id=a.asm.Q).apply(null,arguments)};a._olm_session_has_received_message=function(){return(a._olm_session_has_received_message=a.asm.R).apply(null,arguments)};a._olm_session_describe=function(){return(a._olm_session_describe=a.asm.S).apply(null,arguments)};a._olm_matches_inbound_session=function(){return(a._olm_matches_inbound_session=a.asm.T).apply(null,arguments)};
a._olm_matches_inbound_session_from=function(){return(a._olm_matches_inbound_session_from=a.asm.U).apply(null,arguments)};a._olm_remove_one_time_keys=function(){return(a._olm_remove_one_time_keys=a.asm.V).apply(null,arguments)};a._olm_encrypt_message_type=function(){return(a._olm_encrypt_message_type=a.asm.W).apply(null,arguments)};a._olm_encrypt_random_length=function(){return(a._olm_encrypt_random_length=a.asm.X).apply(null,arguments)};
a._olm_encrypt_message_length=function(){return(a._olm_encrypt_message_length=a.asm.Y).apply(null,arguments)};a._olm_encrypt=function(){return(a._olm_encrypt=a.asm.Z).apply(null,arguments)};a._olm_decrypt_max_plaintext_length=function(){return(a._olm_decrypt_max_plaintext_length=a.asm._).apply(null,arguments)};a._olm_decrypt=function(){return(a._olm_decrypt=a.asm.$).apply(null,arguments)};a._olm_sha256_length=function(){return(a._olm_sha256_length=a.asm.aa).apply(null,arguments)};
a._olm_sha256=function(){return(a._olm_sha256=a.asm.ba).apply(null,arguments)};a._olm_ed25519_verify=function(){return(a._olm_ed25519_verify=a.asm.ca).apply(null,arguments)};a._olm_pk_encryption_last_error=function(){return(a._olm_pk_encryption_last_error=a.asm.da).apply(null,arguments)};a._olm_pk_encryption_size=function(){return(a._olm_pk_encryption_size=a.asm.ea).apply(null,arguments)};a._olm_pk_encryption=function(){return(a._olm_pk_encryption=a.asm.fa).apply(null,arguments)};
a._olm_clear_pk_encryption=function(){return(a._olm_clear_pk_encryption=a.asm.ga).apply(null,arguments)};a._olm_pk_encryption_set_recipient_key=function(){return(a._olm_pk_encryption_set_recipient_key=a.asm.ha).apply(null,arguments)};a._olm_pk_key_length=function(){return(a._olm_pk_key_length=a.asm.ia).apply(null,arguments)};a._olm_pk_ciphertext_length=function(){return(a._olm_pk_ciphertext_length=a.asm.ja).apply(null,arguments)};
a._olm_pk_mac_length=function(){return(a._olm_pk_mac_length=a.asm.ka).apply(null,arguments)};a._olm_pk_encrypt_random_length=function(){return(a._olm_pk_encrypt_random_length=a.asm.la).apply(null,arguments)};a._olm_pk_encrypt=function(){return(a._olm_pk_encrypt=a.asm.ma).apply(null,arguments)};a._olm_pk_decryption_last_error=function(){return(a._olm_pk_decryption_last_error=a.asm.na).apply(null,arguments)};
a._olm_pk_decryption_size=function(){return(a._olm_pk_decryption_size=a.asm.oa).apply(null,arguments)};a._olm_pk_decryption=function(){return(a._olm_pk_decryption=a.asm.pa).apply(null,arguments)};a._olm_clear_pk_decryption=function(){return(a._olm_clear_pk_decryption=a.asm.qa).apply(null,arguments)};a._olm_pk_private_key_length=function(){return(a._olm_pk_private_key_length=a.asm.ra).apply(null,arguments)};
a._olm_pk_generate_key_random_length=function(){return(a._olm_pk_generate_key_random_length=a.asm.sa).apply(null,arguments)};a._olm_pk_key_from_private=function(){return(a._olm_pk_key_from_private=a.asm.ta).apply(null,arguments)};a._olm_pk_generate_key=function(){return(a._olm_pk_generate_key=a.asm.ua).apply(null,arguments)};a._olm_pickle_pk_decryption_length=function(){return(a._olm_pickle_pk_decryption_length=a.asm.va).apply(null,arguments)};
a._olm_pickle_pk_decryption=function(){return(a._olm_pickle_pk_decryption=a.asm.wa).apply(null,arguments)};a._olm_unpickle_pk_decryption=function(){return(a._olm_unpickle_pk_decryption=a.asm.xa).apply(null,arguments)};a._olm_pk_max_plaintext_length=function(){return(a._olm_pk_max_plaintext_length=a.asm.ya).apply(null,arguments)};a._olm_pk_decrypt=function(){return(a._olm_pk_decrypt=a.asm.za).apply(null,arguments)};
a._olm_pk_get_private_key=function(){return(a._olm_pk_get_private_key=a.asm.Aa).apply(null,arguments)};a._olm_pk_signing_size=function(){return(a._olm_pk_signing_size=a.asm.Ba).apply(null,arguments)};a._olm_pk_signing=function(){return(a._olm_pk_signing=a.asm.Ca).apply(null,arguments)};a._olm_pk_signing_last_error=function(){return(a._olm_pk_signing_last_error=a.asm.Da).apply(null,arguments)};a._olm_clear_pk_signing=function(){return(a._olm_clear_pk_signing=a.asm.Ea).apply(null,arguments)};
a._olm_pk_signing_seed_length=function(){return(a._olm_pk_signing_seed_length=a.asm.Fa).apply(null,arguments)};a._olm_pk_signing_public_key_length=function(){return(a._olm_pk_signing_public_key_length=a.asm.Ga).apply(null,arguments)};a._olm_pk_signing_key_from_seed=function(){return(a._olm_pk_signing_key_from_seed=a.asm.Ha).apply(null,arguments)};a._olm_pk_signature_length=function(){return(a._olm_pk_signature_length=a.asm.Ia).apply(null,arguments)};
a._olm_pk_sign=function(){return(a._olm_pk_sign=a.asm.Ja).apply(null,arguments)};a._olm_inbound_group_session_size=function(){return(a._olm_inbound_group_session_size=a.asm.Ka).apply(null,arguments)};a._olm_inbound_group_session=function(){return(a._olm_inbound_group_session=a.asm.La).apply(null,arguments)};a._olm_clear_inbound_group_session=function(){return(a._olm_clear_inbound_group_session=a.asm.Ma).apply(null,arguments)};
a._olm_inbound_group_session_last_error=function(){return(a._olm_inbound_group_session_last_error=a.asm.Na).apply(null,arguments)};a._olm_init_inbound_group_session=function(){return(a._olm_init_inbound_group_session=a.asm.Oa).apply(null,arguments)};a._olm_import_inbound_group_session=function(){return(a._olm_import_inbound_group_session=a.asm.Pa).apply(null,arguments)};a._olm_pickle_inbound_group_session_length=function(){return(a._olm_pickle_inbound_group_session_length=a.asm.Qa).apply(null,arguments)};
a._olm_pickle_inbound_group_session=function(){return(a._olm_pickle_inbound_group_session=a.asm.Ra).apply(null,arguments)};a._olm_unpickle_inbound_group_session=function(){return(a._olm_unpickle_inbound_group_session=a.asm.Sa).apply(null,arguments)};a._olm_group_decrypt_max_plaintext_length=function(){return(a._olm_group_decrypt_max_plaintext_length=a.asm.Ta).apply(null,arguments)};a._olm_group_decrypt=function(){return(a._olm_group_decrypt=a.asm.Ua).apply(null,arguments)};
a._olm_inbound_group_session_id_length=function(){return(a._olm_inbound_group_session_id_length=a.asm.Va).apply(null,arguments)};a._olm_inbound_group_session_id=function(){return(a._olm_inbound_group_session_id=a.asm.Wa).apply(null,arguments)};a._olm_inbound_group_session_first_known_index=function(){return(a._olm_inbound_group_session_first_known_index=a.asm.Xa).apply(null,arguments)};
a._olm_inbound_group_session_is_verified=function(){return(a._olm_inbound_group_session_is_verified=a.asm.Ya).apply(null,arguments)};a._olm_export_inbound_group_session_length=function(){return(a._olm_export_inbound_group_session_length=a.asm.Za).apply(null,arguments)};a._olm_export_inbound_group_session=function(){return(a._olm_export_inbound_group_session=a.asm._a).apply(null,arguments)};
a._olm_outbound_group_session_size=function(){return(a._olm_outbound_group_session_size=a.asm.$a).apply(null,arguments)};a._olm_outbound_group_session=function(){return(a._olm_outbound_group_session=a.asm.ab).apply(null,arguments)};a._olm_clear_outbound_group_session=function(){return(a._olm_clear_outbound_group_session=a.asm.bb).apply(null,arguments)};a._olm_outbound_group_session_last_error=function(){return(a._olm_outbound_group_session_last_error=a.asm.cb).apply(null,arguments)};
a._olm_pickle_outbound_group_session_length=function(){return(a._olm_pickle_outbound_group_session_length=a.asm.db).apply(null,arguments)};a._olm_pickle_outbound_group_session=function(){return(a._olm_pickle_outbound_group_session=a.asm.eb).apply(null,arguments)};a._olm_unpickle_outbound_group_session=function(){return(a._olm_unpickle_outbound_group_session=a.asm.fb).apply(null,arguments)};
a._olm_init_outbound_group_session_random_length=function(){return(a._olm_init_outbound_group_session_random_length=a.asm.gb).apply(null,arguments)};a._olm_init_outbound_group_session=function(){return(a._olm_init_outbound_group_session=a.asm.hb).apply(null,arguments)};a._olm_group_encrypt_message_length=function(){return(a._olm_group_encrypt_message_length=a.asm.ib).apply(null,arguments)};a._olm_group_encrypt=function(){return(a._olm_group_encrypt=a.asm.jb).apply(null,arguments)};
a._olm_outbound_group_session_id_length=function(){return(a._olm_outbound_group_session_id_length=a.asm.kb).apply(null,arguments)};a._olm_outbound_group_session_id=function(){return(a._olm_outbound_group_session_id=a.asm.lb).apply(null,arguments)};a._olm_outbound_group_session_message_index=function(){return(a._olm_outbound_group_session_message_index=a.asm.mb).apply(null,arguments)};
a._olm_outbound_group_session_key_length=function(){return(a._olm_outbound_group_session_key_length=a.asm.nb).apply(null,arguments)};a._olm_outbound_group_session_key=function(){return(a._olm_outbound_group_session_key=a.asm.ob).apply(null,arguments)};a._olm_sas_last_error=function(){return(a._olm_sas_last_error=a.asm.pb).apply(null,arguments)};a._olm_sas_size=function(){return(a._olm_sas_size=a.asm.qb).apply(null,arguments)};a._olm_sas=function(){return(a._olm_sas=a.asm.rb).apply(null,arguments)};
a._olm_clear_sas=function(){return(a._olm_clear_sas=a.asm.sb).apply(null,arguments)};a._olm_create_sas_random_length=function(){return(a._olm_create_sas_random_length=a.asm.tb).apply(null,arguments)};a._olm_create_sas=function(){return(a._olm_create_sas=a.asm.ub).apply(null,arguments)};a._olm_sas_pubkey_length=function(){return(a._olm_sas_pubkey_length=a.asm.vb).apply(null,arguments)};a._olm_sas_get_pubkey=function(){return(a._olm_sas_get_pubkey=a.asm.wb).apply(null,arguments)};
a._olm_sas_set_their_key=function(){return(a._olm_sas_set_their_key=a.asm.xb).apply(null,arguments)};a._olm_sas_generate_bytes=function(){return(a._olm_sas_generate_bytes=a.asm.yb).apply(null,arguments)};a._olm_sas_mac_length=function(){return(a._olm_sas_mac_length=a.asm.zb).apply(null,arguments)};a._olm_sas_calculate_mac=function(){return(a._olm_sas_calculate_mac=a.asm.Ab).apply(null,arguments)};
a._olm_sas_calculate_mac_long_kdf=function(){return(a._olm_sas_calculate_mac_long_kdf=a.asm.Bb).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.Cb).apply(null,arguments)};a._free=function(){return(a._free=a.asm.Db).apply(null,arguments)};var Ra=a.stackSave=function(){return(Ra=a.stackSave=a.asm.Eb).apply(null,arguments)},Sa=a.stackRestore=function(){return(Sa=a.stackRestore=a.asm.Fb).apply(null,arguments)},Ta=a.stackAlloc=function(){return(Ta=a.stackAlloc=a.asm.Gb).apply(null,arguments)};
a.ALLOC_STACK=1;var Ua;Ia=function Va(){Ua||Wa();Ua||(Ia=Va)};
function Wa(){function b(){if(!Ua&&(Ua=!0,a.calledRun=!0,!va)){Oa(Ca);Oa(Da);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();Ea.unshift(c)}Oa(Ea)}}if(!(0<C)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Ga();Oa(Ba);0<C||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
a.run=Wa;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;Wa();function F(){var b=a._olm_outbound_group_session_size();this.Ib=H(b);this.Hb=a._olm_outbound_group_session(this.Ib)}function I(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_outbound_group_session_last_error(arguments[0])),Error("OLM."+c);return c}}F.prototype.free=function(){a._olm_clear_outbound_group_session(this.Hb);J(this.Hb)};
F.prototype.pickle=K(function(b){b=E(b);var c=I(a._olm_pickle_outbound_group_session_length)(this.Hb),d=L(b),e=L(c+1);try{I(a._olm_pickle_outbound_group_session)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});F.prototype.unpickle=K(function(b,c){b=E(b);var d=L(b);c=E(c);var e=L(c);try{I(a._olm_unpickle_outbound_group_session)(this.Hb,d,b.length,e,c.length)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}});
F.prototype.create=K(function(){var b=I(a._olm_init_outbound_group_session_random_length)(this.Hb),c=N(b,g);I(a._olm_init_outbound_group_session)(this.Hb,c,b)});F.prototype.encrypt=function(b){try{var c=B(b);var d=I(a._olm_group_encrypt_message_length)(this.Hb,c);var e=H(c+1);A(b,z,e,c+1);var f=H(d+1);I(a._olm_group_encrypt)(this.Hb,e,c,f,d);t(f+d);return y(f,d)}finally{void 0!==e&&(M(e,c+1),J(e)),void 0!==f&&J(f)}};
F.prototype.session_id=K(function(){var b=I(a._olm_outbound_group_session_id_length)(this.Hb),c=L(b+1);I(a._olm_outbound_group_session_id)(this.Hb,c,b);return y(c,b)});F.prototype.session_key=K(function(){var b=I(a._olm_outbound_group_session_key_length)(this.Hb),c=L(b+1);I(a._olm_outbound_group_session_key)(this.Hb,c,b);var d=y(c,b);M(c,b);return d});F.prototype.message_index=function(){return I(a._olm_outbound_group_session_message_index)(this.Hb)};olm_exports.OutboundGroupSession=F;
function O(){var b=a._olm_inbound_group_session_size();this.Ib=H(b);this.Hb=a._olm_inbound_group_session(this.Ib)}function P(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_inbound_group_session_last_error(arguments[0])),Error("OLM."+c);return c}}O.prototype.free=function(){a._olm_clear_inbound_group_session(this.Hb);J(this.Hb)};
O.prototype.pickle=K(function(b){b=E(b);var c=P(a._olm_pickle_inbound_group_session_length)(this.Hb),d=L(b),e=L(c+1);try{P(a._olm_pickle_inbound_group_session)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});O.prototype.unpickle=K(function(b,c){b=E(b);var d=L(b);c=E(c);var e=L(c);try{P(a._olm_unpickle_inbound_group_session)(this.Hb,d,b.length,e,c.length)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}});
O.prototype.create=K(function(b){b=E(b);var c=L(b);try{P(a._olm_init_inbound_group_session)(this.Hb,c,b.length)}finally{for(M(c,b.length),c=0;c<b.length;c++)b[c]=0}});O.prototype.import_session=K(function(b){b=E(b);var c=L(b);try{P(a._olm_import_inbound_group_session)(this.Hb,c,b.length)}finally{for(M(c,b.length),c=0;c<b.length;c++)b[c]=0}});
O.prototype.decrypt=K(function(b){try{var c=H(b.length);xa(b,c);var d=P(a._olm_group_decrypt_max_plaintext_length)(this.Hb,c,b.length);xa(b,c);var e=H(d+1);var f=L(4);var k=P(a._olm_group_decrypt)(this.Hb,c,b.length,e,d,f);t(e+k);return{plaintext:y(e,k),message_index:ta(f,"i32")}}finally{void 0!==c&&J(c),void 0!==e&&(M(e,k),J(e))}});O.prototype.session_id=K(function(){var b=P(a._olm_inbound_group_session_id_length)(this.Hb),c=L(b+1);P(a._olm_inbound_group_session_id)(this.Hb,c,b);return y(c,b)});
O.prototype.first_known_index=K(function(){return P(a._olm_inbound_group_session_first_known_index)(this.Hb)});O.prototype.export_session=K(function(b){var c=P(a._olm_export_inbound_group_session_length)(this.Hb),d=L(c+1);I(a._olm_export_inbound_group_session)(this.Hb,d,c,b);b=y(d,c);M(d,c);return b});olm_exports.InboundGroupSession=O;function Xa(){var b=a._olm_pk_encryption_size();this.Ib=H(b);this.Hb=a._olm_pk_encryption(this.Ib)}
function Q(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_pk_encryption_last_error(arguments[0])),Error("OLM."+c);return c}}Xa.prototype.free=function(){a._olm_clear_pk_encryption(this.Hb);J(this.Hb)};Xa.prototype.set_recipient_key=K(function(b){b=E(b);var c=L(b);Q(a._olm_pk_encryption_set_recipient_key)(this.Hb,c,b.length)});
Xa.prototype.encrypt=K(function(b){try{var c=B(b);var d=H(c+1);A(b,z,d,c+1);var e=Q(a._olm_pk_encrypt_random_length)();var f=N(e,g);var k=Q(a._olm_pk_ciphertext_length)(this.Hb,c);var p=H(k+1);var v=Q(a._olm_pk_mac_length)(this.Hb),ea=L(v+1);t(ea+v);var S=Q(a._olm_pk_key_length)(),G=L(S+1);t(G+S);Q(a._olm_pk_encrypt)(this.Hb,d,c,p,k,ea,v,G,S,f,e);t(p+k);return{ciphertext:y(p,k),mac:y(ea,v),ephemeral:y(G,S)}}finally{void 0!==f&&M(f,e),void 0!==d&&(M(d,c+1),J(d)),void 0!==p&&J(p)}});
function R(){var b=a._olm_pk_decryption_size();this.Ib=H(b);this.Hb=a._olm_pk_decryption(this.Ib)}function T(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_pk_decryption_last_error(arguments[0])),Error("OLM."+c);return c}}R.prototype.free=function(){a._olm_clear_pk_decryption(this.Hb);J(this.Hb)};
R.prototype.init_with_private_key=K(function(b){var c=L(b.length);a.HEAPU8.set(b,c);var d=T(a._olm_pk_key_length)(),e=L(d+1);try{T(a._olm_pk_key_from_private)(this.Hb,e,d,c,b.length)}finally{M(c,b.length)}return y(e,d)});R.prototype.generate_key=K(function(){var b=T(a._olm_pk_private_key_length)(),c=N(b,g),d=T(a._olm_pk_key_length)(),e=L(d+1);try{T(a._olm_pk_key_from_private)(this.Hb,e,d,c,b)}finally{M(c,b)}return y(e,d)});
R.prototype.get_private_key=K(function(){var b=Q(a._olm_pk_private_key_length)(),c=L(b);T(a._olm_pk_get_private_key)(this.Hb,c,b);var d=new Uint8Array(new Uint8Array(a.HEAPU8.buffer,c,b));M(c,b);return d});R.prototype.pickle=K(function(b){b=E(b);var c=T(a._olm_pickle_pk_decryption_length)(this.Hb),d=L(b),e=L(c+1);try{T(a._olm_pickle_pk_decryption)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});
R.prototype.unpickle=K(function(b,c){b=E(b);var d=L(b),e=E(c),f=L(e);c=T(a._olm_pk_key_length)();var k=L(c+1);try{T(a._olm_unpickle_pk_decryption)(this.Hb,d,b.length,f,e.length,k,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(k,c)});
R.prototype.decrypt=K(function(b,c,d){try{var e=B(d);var f=H(e+1);A(d,z,f,e+1);var k=E(b),p=L(k),v=E(c),ea=L(v);var S=T(a._olm_pk_max_plaintext_length)(this.Hb,e);var G=H(S+1);var Fa=T(a._olm_pk_decrypt)(this.Hb,p,k.length,ea,v.length,f,e,G,S);t(G+Fa);return y(G,Fa)}finally{void 0!==G&&(M(G,Fa+1),J(G)),void 0!==f&&J(f)}});function Ya(){var b=a._olm_pk_signing_size();this.Ib=H(b);this.Hb=a._olm_pk_signing(this.Ib)}
function Za(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_pk_signing_last_error(arguments[0])),Error("OLM."+c);return c}}Ya.prototype.free=function(){a._olm_clear_pk_signing(this.Hb);J(this.Hb)};Ya.prototype.init_with_seed=K(function(b){var c=L(b.length);a.HEAPU8.set(b,c);var d=Za(a._olm_pk_signing_public_key_length)(),e=L(d+1);try{Za(a._olm_pk_signing_key_from_seed)(this.Hb,e,d,c,b.length)}finally{M(c,b.length)}return y(e,d)});
Ya.prototype.generate_seed=K(function(){var b=Za(a._olm_pk_signing_seed_length)(),c=N(b,g),d=new Uint8Array(new Uint8Array(a.HEAPU8.buffer,c,b));M(c,b);return d});Ya.prototype.sign=K(function(b){try{var c=B(b);var d=H(c+1);A(b,z,d,c+1);var e=Za(a._olm_pk_signature_length)(),f=L(e+1);Za(a._olm_pk_sign)(this.Hb,d,c,f,e);return y(f,e)}finally{void 0!==d&&(M(d,c+1),J(d))}});
function U(){var b=a._olm_sas_size(),c=a._olm_create_sas_random_length(),d=N(c,g);this.Ib=H(b);this.Hb=a._olm_sas(this.Ib);a._olm_create_sas(this.Hb,d,c);M(d,c)}function V(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_sas_last_error(arguments[0])),Error("OLM."+c);return c}}U.prototype.free=function(){a._olm_clear_sas(this.Hb);J(this.Hb)};
U.prototype.get_pubkey=K(function(){var b=V(a._olm_sas_pubkey_length)(this.Hb),c=L(b+1);V(a._olm_sas_get_pubkey)(this.Hb,c,b);return y(c,b)});U.prototype.set_their_key=K(function(b){b=E(b);var c=L(b);V(a._olm_sas_set_their_key)(this.Hb,c,b.length)});U.prototype.generate_bytes=K(function(b,c){b=E(b);var d=L(b),e=L(c);V(a._olm_sas_generate_bytes)(this.Hb,d,b.length,e,c);return new Uint8Array(new Uint8Array(a.HEAPU8.buffer,e,c))});
U.prototype.calculate_mac=K(function(b,c){b=E(b);var d=L(b);c=E(c);var e=L(c),f=V(a._olm_sas_mac_length)(this.Hb),k=L(f+1);V(a._olm_sas_calculate_mac)(this.Hb,d,b.length,e,c.length,k,f);return y(k,f)});U.prototype.calculate_mac_long_kdf=K(function(b,c){b=E(b);var d=L(b);c=E(c);var e=L(c),f=V(a._olm_sas_mac_length)(this.Hb),k=L(f+1);V(a._olm_sas_calculate_mac_long_kdf)(this.Hb,d,b.length,e,c.length,k,f);return y(k,f)});var H=a._malloc,J=a._free,h;
function N(b,c){var d=Ta(b);c(new Uint8Array(a.HEAPU8.buffer,d,b));return d}function L(b){return"number"==typeof b?N(b,function(c){c.fill(0)}):N(b.length,function(c){c.set(b)})}function K(b){return function(){var c=Ra();try{return b.apply(this,arguments)}finally{Sa(c)}}}function M(b,c){for(;0<c--;)a.HEAP8[b++]=0}function W(){var b=a._olm_account_size();this.Ib=H(b);this.Hb=a._olm_account(this.Ib)}
function X(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_account_last_error(arguments[0])),Error("OLM."+c);return c}}W.prototype.free=function(){a._olm_clear_account(this.Hb);J(this.Hb)};W.prototype.create=K(function(){var b=X(a._olm_create_account_random_length)(this.Hb),c=N(b,g);X(a._olm_create_account)(this.Hb,c,b)});
W.prototype.identity_keys=K(function(){var b=X(a._olm_account_identity_keys_length)(this.Hb),c=L(b+1);X(a._olm_account_identity_keys)(this.Hb,c,b);return y(c,b)});W.prototype.sign=K(function(b){var c=X(a._olm_account_signature_length)(this.Hb);b=E(b);var d=L(b),e=L(c+1);try{X(a._olm_account_sign)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});
W.prototype.one_time_keys=K(function(){var b=X(a._olm_account_one_time_keys_length)(this.Hb),c=L(b+1);X(a._olm_account_one_time_keys)(this.Hb,c,b);return y(c,b)});W.prototype.mark_keys_as_published=K(function(){X(a._olm_account_mark_keys_as_published)(this.Hb)});W.prototype.max_number_of_one_time_keys=K(function(){return X(a._olm_account_max_number_of_one_time_keys)(this.Hb)});
W.prototype.generate_one_time_keys=K(function(b){var c=X(a._olm_account_generate_one_time_keys_random_length)(this.Hb,b),d=N(c,g);X(a._olm_account_generate_one_time_keys)(this.Hb,b,d,c)});W.prototype.remove_one_time_keys=K(function(b){X(a._olm_remove_one_time_keys)(this.Hb,b.Hb)});
W.prototype.pickle=K(function(b){b=E(b);var c=X(a._olm_pickle_account_length)(this.Hb),d=L(b),e=L(c+1);try{X(a._olm_pickle_account)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});W.prototype.unpickle=K(function(b,c){b=E(b);var d=L(b);c=E(c);var e=L(c);try{X(a._olm_unpickle_account)(this.Hb,d,b.length,e,c.length)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}});function Y(){var b=a._olm_session_size();this.Ib=H(b);this.Hb=a._olm_session(this.Ib)}
function Z(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_session_last_error(arguments[0])),Error("OLM."+c);return c}}Y.prototype.free=function(){a._olm_clear_session(this.Hb);J(this.Hb)};Y.prototype.pickle=K(function(b){b=E(b);var c=Z(a._olm_pickle_session_length)(this.Hb),d=L(b),e=L(c+1);try{Z(a._olm_pickle_session)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});
Y.prototype.unpickle=K(function(b,c){b=E(b);var d=L(b);c=E(c);var e=L(c);try{Z(a._olm_unpickle_session)(this.Hb,d,b.length,e,c.length)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}});Y.prototype.create_outbound=K(function(b,c,d){var e=Z(a._olm_create_outbound_session_random_length)(this.Hb),f=N(e,g);c=E(c);d=E(d);var k=L(c),p=L(d);try{Z(a._olm_create_outbound_session)(this.Hb,b.Hb,k,c.length,p,d.length,f,e)}finally{M(f,e)}});
Y.prototype.create_inbound=K(function(b,c){c=E(c);var d=L(c);try{Z(a._olm_create_inbound_session)(this.Hb,b.Hb,d,c.length)}finally{for(M(d,c.length),b=0;b<c.length;b++)c[b]=0}});Y.prototype.create_inbound_from=K(function(b,c,d){c=E(c);var e=L(c);d=E(d);var f=L(d);try{Z(a._olm_create_inbound_session_from)(this.Hb,b.Hb,e,c.length,f,d.length)}finally{for(M(f,d.length),b=0;b<d.length;b++)d[b]=0}});
Y.prototype.session_id=K(function(){var b=Z(a._olm_session_id_length)(this.Hb),c=L(b+1);Z(a._olm_session_id)(this.Hb,c,b);return y(c,b)});Y.prototype.has_received_message=function(){return Z(a._olm_session_has_received_message)(this.Hb)?!0:!1};Y.prototype.matches_inbound=K(function(b){b=E(b);var c=L(b);return Z(a._olm_matches_inbound_session)(this.Hb,c,b.length)?!0:!1});
Y.prototype.matches_inbound_from=K(function(b,c){b=E(b);var d=L(b);c=E(c);var e=L(c);return Z(a._olm_matches_inbound_session_from)(this.Hb,d,b.length,e,c.length)?!0:!1});
Y.prototype.encrypt=K(function(b){try{var c=Z(a._olm_encrypt_random_length)(this.Hb);var d=Z(a._olm_encrypt_message_type)(this.Hb);var e=B(b);var f=Z(a._olm_encrypt_message_length)(this.Hb,e);var k=N(c,g);var p=H(e+1);A(b,z,p,e+1);var v=H(f+1);Z(a._olm_encrypt)(this.Hb,p,e,k,c,v,f);t(v+f);return{type:d,body:y(v,f)}}finally{void 0!==k&&M(k,c),void 0!==p&&(M(p,e+1),J(p)),void 0!==v&&J(v)}});
Y.prototype.decrypt=K(function(b,c){try{var d=H(c.length);xa(c,d);var e=Z(a._olm_decrypt_max_plaintext_length)(this.Hb,b,d,c.length);xa(c,d);var f=H(e+1);var k=Z(a._olm_decrypt)(this.Hb,b,d,c.length,f,e);t(f+k);return y(f,k)}finally{void 0!==d&&J(d),void 0!==f&&(M(f,e),J(f))}});Y.prototype.describe=K(function(){try{var b=H(256);Z(a._olm_session_describe)(this.Hb,b,256);return y(b)}finally{void 0!==b&&J(b)}});function $a(){var b=a._olm_utility_size();this.Ib=H(b);this.Hb=a._olm_utility(this.Ib)}
function ab(b){return function(){var c=b.apply(this,arguments);if(c===h)throw c=y(a._olm_utility_last_error(arguments[0])),Error("OLM."+c);return c}}$a.prototype.free=function(){a._olm_clear_utility(this.Hb);J(this.Hb)};$a.prototype.sha256=K(function(b){var c=ab(a._olm_sha256_length)(this.Hb);b=E(b);var d=L(b),e=L(c+1);try{ab(a._olm_sha256)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});
$a.prototype.sha256_bytes=K(function(b){var c=ab(a._olm_sha256_length)(this.Hb),d=L(b),e=L(c+1);try{ab(a._olm_sha256)(this.Hb,d,b.length,e,c)}finally{for(M(d,b.length),d=0;d<b.length;d++)b[d]=0}return y(e,c)});$a.prototype.ed25519_verify=K(function(b,c,d){b=E(b);var e=L(b);c=E(c);var f=L(c);d=E(d);var k=L(d);try{ab(a._olm_ed25519_verify)(this.Hb,e,b.length,f,c.length,k,d.length)}finally{for(M(f,c.length),b=0;b<c.length;b++)c[b]=0}});olm_exports.Account=W;olm_exports.Session=Y;
olm_exports.Utility=$a;olm_exports.PkEncryption=Xa;olm_exports.PkDecryption=R;olm_exports.PkSigning=Ya;olm_exports.SAS=U;olm_exports.get_library_version=K(function(){var b=L(3);a._olm_get_library_version(b,b+1,b+2);return[ta(b,"i8"),ta(b+1,"i8"),ta(b+2,"i8")]});


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
var olmInitPromise;

olm_exports['init'] = function(opts) {
    if (olmInitPromise) return olmInitPromise;

    if (opts) OLM_OPTIONS = opts;

    olmInitPromise = new Promise(function(resolve, reject) {
        onInitSuccess = function() {
            resolve();
        };
        onInitFail = function(err) {
            reject(err);
        };
        Module();
    });
    return olmInitPromise;
};

if (typeof(window) !== 'undefined') {
    // We've been imported directly into a browser. Define the global 'Olm' object.
    // (we do this even if module.exports was defined, because it's useful to have
    // Olm in the global scope for browserified and webpacked apps.)
    window["Olm"] = olm_exports;
}

if (typeof module === 'object') {
    // Emscripten sets the module exports to be its module
    // with wrapped c functions. Clobber it with our higher
    // level wrapper class.
    module.exports = olm_exports;
}
