name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  ANDROID_NDK_HOME: /home/runner/android-ndk-r26d
  ANDROID_NDK: /home/runner/android-ndk-r26d

jobs:
  build-android:
    name: Build (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # From freya:
      - name: Install NDK r26d
        run: |
          curl -sSfL -o ndk.zip https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q ndk.zip -d /home/runner
          rm ndk.zip
 
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.0.12077973"

      - name: Build APK
        working-directory: AndroidApp
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/27.0.12077973
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: AndroidApp/app/build/outputs/apk/debug/app-debug.apk
